projects:
  'AWS Chat ':
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: vyzh2kodk5aeff4skt66yrvawm
        maxDepth: 2
extensions:
  amplify:
    version: 3
