// This is the home page
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Chat from './chat';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contactoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Contactoo Customer Service!</h1>
        <br />
        <br />
        <p className={styles.card}>
          <input
            type="text"
            name="searchBar"
            placeholder="Search services..."
          />
          <button type="">Search</button>
        </p>

        <div className={styles.grid}>
          {/* Replace localhost with s3 bucket address after hosting on Amazon S3 Bucket */}
          <a href="http://localhost:3000/email" className={styles.card}>
            <h2>Email Us &rarr;</h2>
            <p>Email us regarding your questions, comments, or concerns.</p>
          </a>

          {/* Replace localhost with s3 bucket address after hosting on Amazon S3 Bucket */}
          <a href="http://localhost:3000/message" className={styles.card}>
            <h2>Message Us &rarr;</h2>
            <p>Message us regarding your questions, comments, or concerns.</p>
          </a>

          {/* Replace localhost with s3 bucket address after hosting on Amazon S3 Bucket */}
          <a href="http://localhost:3000/chat" className={styles.card}>
            <h2>Chat &rarr;</h2>
            <p>Chat with the retailer.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
